version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "test-code-build-thanhtt1"

phases:
  install:
    runtime-versions:
      nodejs: 22  # or 18, whichever your app supports
    commands:
      - echo Installing Node.js and npm
      - npm install -g npm@latest  # Update npm to latest version
      # - echo "Installing AWS CLI"
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - ./aws/install

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://${S3_BUCKET_NAME} --delete

artifacts:
  files:
    - '**/*'
  base-directory: 'build'